branches:
  only:
    - master
language: ruby
rvm:
  - 2.1.5
bundler_args: --binstubs --retry=5 --path=.bundle
cache:
  directories:
    - .bundle
before_script:
  - /bin/echo '--color' > .rspec
env:
  - TEST_SUITE=linters
script: bundle exec rake $TEST_SUITE
